### ISSUE TITLE
Can't show anything

### ISSUE THREAD

**Issue by xclidongbo** [react-native-community/art#20]
# Bug

## Environment info

React native info output:

React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 1.54 GB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 27
        Build Tools: 27.0.3
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

```
import {
    Surface,
    Group,
    Shape,
    LinearGradient,
    Path,
    Transform,
    ClippingRectangle,
} from '@react-native-community/art';

export class ARTPage extends Component {
    render() {
        const path = new Path();
        path.moveTo(1,1); //将起始点移动到(1,1) 默认(0,0)
        path.lineTo(300,1); //连线到目标点(300,1)
        return (
            <View style={this.props.style}>
                <Surface width={500} height={500}>
                <Shape d={new Path().moveTo(0, 0).lineTo(200, 200)} fill="#d39494" />
                </Surface>
            </View>

        )
    }
}

```
...

Describe what you expected to happen:

1.
2.

**Comment by talal7860** [comment]
Hey @xclidongbo 
I'm having the same issue, would you mind sharing on the steps to fix this?

**Comment by ruandao** [comment]
i get the same problem
