### ISSUE TITLE
ART don't work

### ISSUE THREAD

**Issue by wangfpp** [react-native-community/art#24]
ART Shape don't work

## Environment info

```bash
react-native info
info 
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
      Memory: 631.46 MB / 15.55 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

Library version: 1.0.1
"@react-native-community/art": "^1.0.1",
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/netinfo": "^3.2.1",
    "axios": "^0.19.0",
    "native-base": "^2.13.4",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-drawer": "^2.5.1",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-size": "^1.1.2",
    "react-native-orientation-locker": "^1.1.6",
    "react-native-storage": "^1.0.1",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.1"

## MyCode:
```javascript
import React, { Component } from 'react';
import { View, StyleSheet } from 'react-native';
import {
    Surface,
    ClippingRectangle,
    Shape,
    Path,
  } from '@react-native-community/art';
class drawer extends Component {
    render() {
        let path = new Path();
		path.moveTo(0,0);
		path.lineTo(100,0);
		path.lineTo(100,100),
		path.lineTo(0,100);
		path.close();
       return(
        <View style={styles.app}>
       <Surface width={500} height={500}>
      <Shape d={new Path().moveTo(0, 0).lineTo(200, 200)} fill="#d39494" stroke="#f00" strokeWidth={20} width={500} height={500}/>
    </Surface>
    </View>
       )
    }
};
const styles = StyleSheet.create({
    app: {
        flex: 1
    },
    surface: {
        backgroundColor: '#f00'
    }
})
```

## Render Result:
![2019-08-05 11-24-59 的屏幕截图](https://user-images.githubusercontent.com/35289556/62436913-b78b6a00-b773-11e9-9a54-596b48712de9.png)

**Comment by Esemesek** [comment]
I had similar issues in the past with the module. Can you wrap the whole thing in `ScrollView` like in the example? https://github.com/react-native-community/art/blob/master/example/App.js

As far as I know, you need to wrap Surfaces in ScrollViews on Android. I have no idea why this is happening, but this bug is carried over from ReactNative.

**Comment by wangfpp** [comment]
@Esemesek 　Thank you, I give up 💔    
try react-native-svg    
forgive my poor english😖
