### ISSUE TITLE
Error upon installing 1.0.1

### ISSUE THREAD

**Issue by swatkns785** [react-native-community/art#25]
SyntaxError: /<MY_PATH>/node_modules/@react-native-community/art/lib/ARTSerializablePath.js: Unexpected token, expected "," (21:27)

  19 | // TODO: Refactor to class
  20 | const SerializablePath = Class(Path, {
> 21 |   initialize: function(path: string | SerializablePath) {
     |                            ^
  22 |     this.reset();
  23 |     if (path instanceof SerializablePath) {
  24 |       this.path = path.path.slice(0);

Any ideas on how to resolve this issue?

**Comment by Esemesek** [comment]
Can you create a demo with a reproduction of this exact issue?

**Comment by adrian-moisa** [comment]
I have the same exact issue with `"@react-native-community/art": "1.1.2",`. Have you found any useful information?
