### ISSUE TITLE
duplicate interface definition for class 'art brush'

### ISSUE THREAD

**Issue by pegasus1982** [react-native-community/art#40]
I installed this package to use Circle progress (React-Native-Progress).
RN: 0.60.5
React-Native-Progress: 4.0.1

After installing pod, I got this issue.

I'm not sure it is interact with RN-SVG, coz I have installed React-Native-SVG also.
Please help

**Comment by saadkhan6670** [comment]
Had the same issue i just removed this line from podfile 
![image](https://user-images.githubusercontent.com/6495045/68399631-823e5000-0198-11ea-9208-96b5109f3c27.png)
and did a pod install after deleting the podlock and POD file because now react native uses its own ART library very well

**Comment by mitesh-db** [comment]
Hey it gives me `ld: library not found for -lReact-ART` Error after removing pod
