### ISSUE TITLE
Android - v1.0.3 Broke Stroke. Crashes device

### ISSUE THREAD

**Issue by bayoremit** [react-native-community/art#42]
# Bug

Setting any stroke prop on android crashes the device. On the bright side, it now works on iOS :)

Currently using it w/ react-native-svg

NOTE: Used to work in v1.0.2

## Environment info

```
Expo CLI 3.4.1 environment info:
System:
    OS: macOS 10.15.1
    Shell: 5.7.1 - /bin/zsh
Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
npmPackages:
    expo: 35.0.1 => 35.0.1
    react: 16.8.3 => 16.8.3 
    react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
npmGlobalPackages:
    expo-cli: 3.4.1
```

## Steps To Reproduce

-> Demo

## Expected Behavior

Svg to be displayed

## Actual Behavior

Device crashes

[Imgur: Error Screenshot](https://imgur.com/a/ffY7BcE)

## Reproducible sample code

`android.svg`
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 105">
    <g fill="#97C024" stroke="#97C024" stroke-linejoin="round" stroke-linecap="round">
        <path d="M14,40v24M81,40v24M38,68v24M57,68v24M28,42v31h39v-31z" stroke-width="12" />
        <path d="M32,5l5,10M64,5l-6,10 " stroke-width="2" />
    </g>
    <path d="M22,35h51v10h-51zM22,33c0-31,51-31,51,0" fill="#97C024" />
    <g fill="#FFF">
        <circle cx="36" cy="22" r="2" />
        <circle cx="59" cy="22" r="2" />
    </g>
</svg>
```

`android.tsx`
```tsx
import React, { FC } from "react";
import { SvgProps } from "react-native-svg";

import AndroidSvg from "./android.svg";

export const Android: FC<SvgProps> = ({
    fill = "#97C024",
    ...rest
}) => {

    return <AndroidSvg fill={fill} {...rest} />;
};
```

**Comment by gkbroderick** [comment]
Experiencing the same error. Had to pin the package to 1.0.2 to fix Android. Luckily usage was simple enough it seems to be okay on iOS as well.

**Comment by shwetsolanki** [comment]
@bayoremit could you share a sample project so that I can look into it?

**Comment by bayoremit** [comment]
> Experiencing the same error. Had to pin the package to 1.0.2 to fix Android. Luckily usage was simple enough it seems to be okay on iOS as well.

Yup, that is the solution we went with too.

For those using a lib that relies on react-art and not using it directly. This is how we did it w/ yarn.

Add this to your package.json file

```json
...
    "devDependencies": {
        "@types/node": "12.12.14",
        "@types/react": "16.8.23",
        "typescript": "3.7.2"
    },
    "resolutions": {
        "**/@react-native-community/art": "1.0.2"
    },
...
```

**Comment by bayoremit** [comment]
@shwetsolanki I will get one setup

**Comment by Esemesek** [comment]
Can you create some kind of demo with this crash?

**Comment by Esemesek** [comment]
This is now fixed.

**Comment by bayoremit** [comment]
Sorry, have been swamped but thanks for the quick fix. I'll make the update, test, and report back
